language: cpp
compiler: gcc

matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - gcc-4.9
            - g++-4.9-multilib
            - gcc-4.9-multilib
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
  - echo "before install"
  - eval "${MATRIX_EVAL}"
  - arch
  - sudo ls /etc/dpkg/dpkg.cfg.d/
  - sudo sh -c "echo 'foreign-architecture i386' > /etc/dpkg/dpkg.cfg.d/multiarch"
  - sudo ls /etc/dpkg/dpkg.cfg.d/
  - sudo apt-get update
  - sudo apt-get install nasm:i386 paxctl:i386 libtommath-dev:i386
  
  # stackoverflow magic, didn't actually check why .. but works
  - sudo ln -s /usr/include/asm-generic /usr/include/asm

script: 
  - make
